/**
 * Проекты — общий источник для ленты и для /projects.
 *
 * Раньше каталог был захардкожен прямо в app/projects/page.tsx (4 записи без
 * дат), а лента рисовала одну большую статичную карточку. Карусели ленты
 * и фильтры каталога нуждаются в датах, просмотрах и тематиках, поэтому
 * набор вырос до 20 проектов: на пять тем иначе приходится по 2-3 карточки,
 * и листать нечего.
 */

/** Темы каталога. Проект может попадать сразу в несколько — интерьерные
 *  работы почти всегда ещё и дизайн, поэтому одна строка `tag` не годится. */
export const PROJECT_TOPICS = [
  "Интерьер",
  "Дизайн",
  "Ремонт",
  "Дом",
  "Ландшафт",
] as const;

export type ProjectTopic = (typeof PROJECT_TOPICS)[number];

export interface FeedProject {
  id: string;
  title: string;
  author: string;
  authorRole: string;
  location: string;
  /** Основная подпись на карточке. */
  tag: string;
  topics: ProjectTopic[];
  likes: number;
  views: number;
  /** Бюджет проекта в евро — показывается в карточке. */
  budget: number;
  photos: number;
  specialists: number;
  createdAt: number;
  coverUrl: string;
}

const HOUR = 1000 * 60 * 60;
const DAY = HOUR * 24;

export const SEED_PROJECTS: FeedProject[] = [
  {
    id: "modern-kitchen",
    title: "Кухня в современном стиле",
    author: "Мария Смирнова",
    authorRole: "Дизайнер интерьеров",
    location: "Rotterdam",
    tag: "Интерьер",
    topics: ["Интерьер", "Дизайн"],
    likes: 128,
    views: 2140,
    budget: 46000,
    photos: 18,
    specialists: 3,
    createdAt: Date.now() - 3 * HOUR,
    coverUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "scandi-house",
    title: "Загородный дом в скандинавском стиле",
    author: "Алексей Петров",
    authorRole: "Архитектор",
    location: "Utrecht",
    tag: "Дом",
    topics: ["Дом"],
    likes: 96,
    views: 1730,
    budget: 128000,
    photos: 32,
    specialists: 6,
    createdAt: Date.now() - 9 * HOUR,
    coverUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "bathroom-renovation",
    title: "Ремонт ванной комнаты",
    author: "Анна К.",
    authorRole: "Заказчик",
    location: "Rotterdam",
    tag: "Ремонт",
    topics: ["Ремонт"],
    likes: 74,
    views: 1180,
    budget: 18500,
    photos: 11,
    specialists: 4,
    createdAt: Date.now() - 1 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "terrace-landscape",
    title: "Терраса и ландшафт участка",
    author: "Дмитрий Орлов",
    authorRole: "Ландшафтный дизайнер",
    location: "Delft",
    tag: "Ландшафт",
    topics: ["Ландшафт"],
    likes: 61,
    views: 940,
    budget: 32000,
    photos: 22,
    specialists: 5,
    createdAt: Date.now() - 2 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "loft-living",
    title: "Лофт-гостиная с кирпичной стеной",
    author: "Ирина Волкова",
    authorRole: "Дизайнер интерьеров",
    location: "Amsterdam",
    tag: "Интерьер",
    topics: ["Интерьер", "Дизайн"],
    likes: 143,
    views: 2610,
    budget: 54000,
    photos: 27,
    specialists: 4,
    createdAt: Date.now() - 3 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "studio-flat",
    title: "Студия 34 м²: всё на 6 кв. метрах",
    author: "Павел Никитин",
    authorRole: "Заказчик",
    location: "Rotterdam",
    tag: "Интерьер",
    topics: ["Интерьер", "Дизайн"],
    likes: 88,
    views: 1520,
    budget: 22000,
    photos: 9,
    specialists: 2,
    createdAt: Date.now() - 4 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "garden-house",
    title: "Садовая беседка из клеёного бруса",
    author: "Сергей Кузьмин",
    authorRole: "Плотник",
    location: "Utrecht",
    tag: "Дом",
    topics: ["Дом"],
    likes: 52,
    views: 760,
    budget: 27000,
    photos: 14,
    specialists: 3,
    createdAt: Date.now() - 5 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "basement-finish",
    title: "Подвал в жилой кабинет",
    author: "Ольга Белова",
    authorRole: "Заказчик",
    location: "Delft",
    tag: "Ремонт",
    topics: ["Ремонт"],
    likes: 47,
    views: 690,
    budget: 19000,
    photos: 12,
    specialists: 4,
    createdAt: Date.now() - 6 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "bath-mat",
    title: "Ванная комната в тёплых тонах",
    author: "Егор Лапин",
    authorRole: "Мастер отделочных работ",
    location: "Rotterdam",
    tag: "Ремонт",
    topics: ["Ремонт"],
    likes: 39,
    views: 540,
    budget: 16500,
    photos: 8,
    specialists: 3,
    createdAt: Date.now() - 7 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "courtyard",
    title: "Двор с террасой и зоной отдыха",
    author: "Наталья Жук",
    authorRole: "Ландшафтный дизайнер",
    location: "Amsterdam",
    tag: "Ландшафт",
    topics: ["Ландшафт"],
    likes: 66,
    views: 1050,
    budget: 41000,
    photos: 20,
    specialists: 5,
    createdAt: Date.now() - 9 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=1200&q=85",
  },

  // Дальше проекты добавлены вместе с фильтрами каталога: чтобы «Новые» и
  // «Популярные» отличались порядком, а не совпадали, даты и просмотры
  // разведены (свежие не самые популярные и наоборот).
  {
    id: "visualization-concept",
    title: "Визуализация двушки по дизайн-проекту",
    author: "Ксения Мельник",
    authorRole: "Визуализатор",
    location: "Rotterdam",
    tag: "Дизайн",
    topics: ["Дизайн"],
    likes: 112,
    views: 2980,
    budget: 2400,
    photos: 16,
    specialists: 1,
    createdAt: Date.now() - 12 * HOUR,
    coverUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "fireplace-living",
    title: "Гостиная с камином и книжными шкафами",
    author: "Ирина Волкова",
    authorRole: "Дизайнер интерьеров",
    location: "Amsterdam",
    tag: "Интерьер",
    topics: ["Интерьер", "Дизайн"],
    likes: 121,
    views: 2240,
    budget: 63000,
    photos: 24,
    specialists: 4,
    createdAt: Date.now() - 11 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "house-design-project",
    title: "Проект дома 120 м² под ключ",
    author: "Алексей Петров",
    authorRole: "Архитектор",
    location: "Utrecht",
    tag: "Дом",
    topics: ["Дом", "Дизайн"],
    likes: 87,
    views: 1620,
    budget: 145000,
    photos: 30,
    specialists: 6,
    createdAt: Date.now() - 14 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "nineties-apartment",
    title: "Квартира 90-х без демонтажа",
    author: "Дмитрий Орлов",
    authorRole: "Заказчик",
    location: "Rotterdam",
    tag: "Ремонт",
    topics: ["Ремонт", "Интерьер"],
    likes: 95,
    views: 1880,
    budget: 78000,
    photos: 21,
    specialists: 5,
    createdAt: Date.now() - 18 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "frame-house",
    title: "Каркасный дом 90 м² за сезон",
    author: "Сергей Кузьмин",
    authorRole: "Плотник",
    location: "Delft",
    tag: "Дом",
    topics: ["Дом"],
    likes: 58,
    views: 830,
    budget: 96000,
    photos: 19,
    specialists: 4,
    createdAt: Date.now() - 26 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "garden-paths",
    title: "Дорожки и отмостка на участке",
    author: "Наталья Жук",
    authorRole: "Ландшафтный дизайнер",
    location: "Amsterdam",
    tag: "Ландшафт",
    topics: ["Ландшафт"],
    likes: 44,
    views: 610,
    budget: 23000,
    photos: 15,
    specialists: 3,
    createdAt: Date.now() - 34 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "office-renovation",
    title: "Офис open space на 18 рабочих мест",
    author: "Ксения Мельник",
    authorRole: "Дизайнер интерьеров",
    location: "Rotterdam",
    tag: "Ремонт",
    topics: ["Ремонт", "Дизайн"],
    likes: 78,
    views: 1420,
    budget: 88000,
    photos: 17,
    specialists: 5,
    createdAt: Date.now() - 41 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "facade-repaint",
    title: "Перекраска фасада и обновление цоколя",
    author: "Егор Лапин",
    authorRole: "Мастер отделочных работ",
    location: "Delft",
    tag: "Ремонт",
    topics: ["Ремонт"],
    likes: 31,
    views: 420,
    budget: 14500,
    photos: 10,
    specialists: 2,
    createdAt: Date.now() - 52 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1591588582259-e675bd2e6088?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "terrace-deck",
    title: "Настил террасы из лиственницы",
    author: "Павел Никитин",
    authorRole: "Заказчик",
    location: "Utrecht",
    tag: "Ландшафт",
    topics: ["Ландшафт", "Дом"],
    likes: 49,
    views: 720,
    budget: 19500,
    photos: 12,
    specialists: 2,
    createdAt: Date.now() - 63 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "kindergarten-design",
    title: "Дизайн-проект детского сада",
    author: "Ольга Белова",
    authorRole: "Архитектор",
    location: "Amsterdam",
    tag: "Дизайн",
    topics: ["Дизайн"],
    likes: 69,
    views: 1310,
    budget: 34000,
    photos: 23,
    specialists: 4,
    createdAt: Date.now() - 78 * DAY,
    coverUrl: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=1200&q=85",
  },
];

/** Порядок для «свежих» — новые сверху. */
export function projectsByNewest(list: FeedProject[]): FeedProject[] {
  return [...list].sort((a, b) => b.createdAt - a.createdAt);
}
