import { Order } from "./types";

function placeholder(bg: string, label: string): string {
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300'>
    <rect width='100%' height='100%' fill='${bg}'/>
    <text x='50%' y='50%' font-family='sans-serif' font-size='22' fill='#ffffff'
      text-anchor='middle' dominant-baseline='middle'>${label}</text>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

export const SEED_ORDERS: Order[] = [
  {
    id: "seed-1",
    code: "XKPQ-48213",
    category: "Инженерный монтаж (Электрика)",
    subcategory: "Электрощит и автоматы",
    serviceName: "Сборка и подключение ВРУ (щитка) с УЗО, дифавтоматами, реле напряжения",
    areaSqm: 62,
    areaOver1000: false,
    address: "ул. Садовая, 14, кв. 27",
    premise: "secondary",
    condition: "rough",
    budgetMin: 25000,
    budgetMax: 40000,
    deadlineDays: 5,
    description:
      "Нужно собрать и повесить новый щиток на 24 модуля, старый пришёл в негодность. Автоматы и УЗО можно свои посоветовать — готовы закупить.",
    media: [{ id: "m1", dataUrl: placeholder("#00A86B", "Электрощиток"), isCover: true }],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 40,
    authorRole: "customer",
    distanceKm: 1.2,
    views: 34,
    status: "open",
  },
  {
    id: "seed-2",
    code: "TMNR-70642",
    category: "Отделочные работы (Интерьер)",
    subcategory: "Плиточные работы",
    serviceName: "Укладка керамической плитки, керамогранита и мозаики",
    areaSqm: 18,
    areaOver1000: false,
    address: "ЖК «Northside», корп. 2, кв. 84",
    premise: "new",
    condition: "rough",
    budgetMin: 35000,
    budgetMax: 60000,
    budgetPerSqmMin: 1800,
    budgetPerSqmMax: 2500,
    deadlineDays: 3,
    description:
      "Ванная комната в новостройке, стены и пол, плитка уже куплена (керамогранит 60х60). Нужна ровная раскладка без подрезки на видных местах.",
    media: [
      { id: "m2", dataUrl: placeholder("#468966", "Плитка, ванная"), isCover: true },
    ],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 120,
    authorRole: "customer",
    distanceKm: 3.4,
    views: 51,
    status: "open",
  },
  {
    id: "seed-3",
    code: "HVCB-19384",
    category: "Инженерный монтаж (Сантехника)",
    subcategory: "Установка приборов",
    serviceName: "Установка унитазов, биде, ванн, душевых кабин и смесителей",
    areaSqm: 8,
    areaOver1000: false,
    address: "пр. Ленина, 58, кв. 12",
    premise: "secondary",
    condition: "finished",
    budgetMin: 8000,
    budgetMax: 15000,
    deadlineDays: 14,
    description:
      "Течёт смеситель на кухне и подтекает сифон под мойкой. Нужно заменить смеситель (куплен) и проверить всю разводку под мойкой.",
    media: [{ id: "m3", dataUrl: placeholder("#5E6E67", "Течь под мойкой"), isCover: true }],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 200,
    authorRole: "customer",
    distanceKm: 0.8,
    views: 12,
    status: "open",
  },
  {
    id: "seed-4",
    code: "AJWY-53927",
    category: "Строительство частных домов",
    subcategory: "Кровельные работы",
    serviceName:
      "Монтаж стропильной системы и кровли (металлочерепица, профнастил, мягкая черепица)",
    areaSqm: 120,
    areaOver1000: false,
    address: "СНТ «Ромашка», уч. 45",
    premise: "country",
    condition: "rough",
    budgetMin: 150000,
    budgetMax: 220000,
    budgetPerSqmMin: 1200,
    budgetPerSqmMax: 1800,
    deadlineDays: 10,
    description:
      "Двухскатная крыша дома 10х12 м, нужна полная стропильная система и кровля из металлочерепицы. Проект есть, могу прислать по запросу в чате.",
    media: [{ id: "m4", dataUrl: placeholder("#22302B", "Кровля, скат"), isCover: true }],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 300,
    authorRole: "customer",
    distanceKm: 12.6,
    views: 8,
    status: "open",
  },
  // Ниже — заказы, добавленные вместе с каруселями ленты: «Нужны мастера»
  // показывает 10 свежих задач, а на старте было всего четыре сида, из-за
  // чего карусель выглядела пустой. Даты разнесены, чтобы «новые» и
  // «популярные» в ленте давали разный порядок.
  {
    id: "seed-5",
    code: "PSLV-30518",
    category: "Отделочные работы (Интерьер)",
    subcategory: "Малярные работы",
    serviceName: "Выравнивание стен и поклейка обоев под покраску",
    areaSqm: 74,
    areaOver1000: false,
    address: "ул. Корвинтерн, 9, кв. 112",
    premise: "secondary",
    condition: "rough",
    budgetMin: 42000,
    budgetMax: 58000,
    budgetPerSqmMin: 550,
    budgetPerSqmMax: 780,
    deadlineDays: 14,
    description:
      "Нужно подготовить стены под покраску: штукатурка, шпаклёвка в два слоя, грунт. Поклейка обоев — только на две комнаты. Объём большой, работаем по этапам.",
    media: [{ id: "m5", dataUrl: placeholder("#8A6A4F", "Стены, штукатурка"), isCover: true }],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 55,
    authorRole: "customer",
    distanceKm: 3.4,
    views: 21,
    status: "open",
  },
  {
    id: "seed-6",
    code: "SNTS-81274",
    category: "Инженерный монтаж (Сантехника)",
    subcategory: "Сантехника",
    serviceName: "Замена стояков и разводка сантехники в ванной",
    areaSqm: 12,
    areaOver1000: false,
    address: "Кленовая ул., 44, кв. 6",
    premise: "secondary",
    condition: "finished",
    budgetMin: 28000,
    budgetMax: 39000,
    deadlineDays: 7,
    description:
      "Стояк горячей и холодной воды, перевести смесители на скрытый монтаж, поставить душевую кабину и унитаз подвесной. Старые чугунные трубы уже демонтированы.",
    media: [{ id: "m6", dataUrl: placeholder("#2F6D8A", "Сантехника, трубы"), isCover: true }],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 130,
    authorRole: "customer",
    distanceKm: 5.1,
    views: 47,
    status: "open",
  },
  {
    id: "seed-7",
    code: "OTPL-64903",
    category: "Инженерный монтаж (Отопление и вентиляция)",
    subcategory: "Отопление",
    serviceName: "Монтаж радиаторов, коллекторов и тёплого пола",
    areaSqm: 96,
    areaOver1000: false,
    address: "ул. Мальчикова, 17, кв. 55",
    premise: "new",
    condition: "rough",
    budgetMin: 68000,
    budgetMax: 95000,
    deadlineDays: 21,
    description:
      "Квартира на черновой стадии. Нужны радиаторы с терморегуляторами, коллекторный шкаф и тёплый пол на первом этаже. Проект и расчёты есть, работаем по этапам.",
    media: [{ id: "m7", dataUrl: placeholder("#6A4E3A", "Радиаторы, тёплый пол"), isCover: true }],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 190,
    authorRole: "customer",
    distanceKm: 9.8,
    views: 63,
    status: "open",
  },
  {
    id: "seed-8",
    code: "STRM-27741",
    category: "Строительство частных домов",
    subcategory: "Коробка",
    serviceName: "Коробка из газобетона, фундамент и перекрытие",
    areaSqm: 148,
    areaOver1000: false,
    address: "г. Борг, Холмовая ул., 12",
    premise: "country",
    condition: "rough",
    budgetMin: 320000,
    budgetMax: 450000,
    deadlineDays: 45,
    description:
      "Дом 10×14, два этажа, газобетон D400. Нужны ленточный фундамент с утеплением, коробка и перекрытие. Геология есть, проект в наличии, можно обсудить график платежей.",
    media: [{ id: "m8", dataUrl: placeholder("#5B6B5F", "Коробка дома"), isCover: true }],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 320,
    authorRole: "customer",
    distanceKm: 18.2,
    views: 91,
    status: "open",
  },
  {
    id: "seed-9",
    code: "KLNG-50668",
    category: "Клининг и вывоз мусора",
    subcategory: "Уборка после ремонта",
    serviceName: "Генеральная уборка после ремонта квартиры 2-комн.",
    areaSqm: 58,
    areaOver1000: false,
    address: "пр. Корвум, 38, кв. 14",
    premise: "secondary",
    condition: "finished",
    budgetMin: 9000,
    budgetMax: 14000,
    deadlineDays: 2,
    description:
      "Ремонт закончили, нужна генеральная уборка: окна, полы, сантехника, пыль со всех поверхностей. Плюс вывоз мешков с мусором — около 6 мешков.",
    media: [],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 25,
    authorRole: "customer",
    distanceKm: 2.1,
    views: 15,
    status: "open",
  },
  {
    id: "seed-10",
    code: "CHRZ-13950",
    category: "Черновые работы",
    subcategory: "Демонтаж",
    serviceName: "Демонтаж перегородок и вынос строительного мусора",
    areaSqm: 40,
    areaOver1000: false,
    address: "ул. Вильгельмина, 61",
    premise: "secondary",
    condition: "rough",
    budgetMin: 12000,
    budgetMax: 18000,
    deadlineDays: 4,
    description:
      "Нужно снести две ненесущие перегородки, снять старый пол и ламинат. Мусор строительный, вынести и вывезти. Работа на один день, доступ с утра.",
    media: [{ id: "m10", dataUrl: placeholder("#4A4A48", "Демонтаж"), isCover: true }],
    documents: [],
    createdAt: Date.now() - 1000 * 60 * 95,
    authorRole: "customer",
    distanceKm: 6.7,
    views: 29,
    status: "open",
  },
];
