import { Article } from "./types";

function cover(bg: string, label: string): string {
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='400' height='240'>
    <rect width='100%' height='100%' fill='${bg}'/>
    <text x='50%' y='50%' font-family='sans-serif' font-size='18' fill='#ffffff'
      text-anchor='middle' dominant-baseline='middle'>${label}</text>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

export const SEED_ARTICLES: Article[] = [
  {
    id: "art-1",
    kind: "article",
    topic: "design",
    title: "5 ошибок при выборе плитки для ванной",
    excerpt: "Разбираем частые промахи: от неверного расчёта запаса до раскладки без учёта подрезки.",
    content:
      "Полный текст статьи о выборе плитки: расчёт запаса с учётом подрезки, разница между матовой и глянцевой поверхностью, на что смотреть при выборе клея и затирки.",
    coverUrl: cover("#FF6B1A", "Плитка"),
    authorName: "Дизайнер Анна К.",
    promoted: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    views: 214,
    clicks: 0,
    likes: 42,
  },
  {
    id: "art-2",
    kind: "news",
    topic: "market",
    title: "Цены на арматуру снизились на 6% за квартал",
    excerpt: "Аналитики связывают это с сезонным спадом спроса и ростом внутреннего производства.",
    content: "Подробности новости о ценах на арматуру и прогнозы на следующий квартал.",
    coverUrl: cover("#2B2D31", "Новости рынка"),
    authorName: "Редакция UMELO",
    promoted: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 10,
    views: 98,
    clicks: 0,
    likes: 18,
  },
  {
    id: "art-3",
    kind: "promo",
    topic: "deals",
    title: "−20% на сухие смеси Кнауф до конца месяца",
    excerpt: "Акция у партнёра-поставщика: скидка при заказе от 500 кг с доставкой по городу.",
    content: "Условия акции, контакты поставщика, зона доставки.",
    coverUrl: cover("#1F8A55", "Акция"),
    authorName: "СтройБаза Партнёр",
    promoted: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
    views: 340,
    clicks: 27,
    likes: 31,
    linkUrl: "https://example.com/stroybaza-promo",
  },
  {
    id: "art-3b",
    kind: "promo",
    topic: "tools",
    title: "−15% на аккумуляторные шуруповёрты",
    excerpt: "Партнёрский магазин инструмента: скидка при предъявлении промокода UMELO15.",
    content: "Условия акции, список моделей со скидкой, адреса магазинов-партнёров.",
    coverUrl: cover("#FF6B1A", "Инструменты"),
    authorName: "ИнструментПро",
    promoted: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 6,
    views: 156,
    clicks: 11,
    likes: 15,
    linkUrl: "https://example.com/instrumentpro-promo",
  },
  {
    id: "art-4",
    kind: "article",
    topic: "tools",
    title: "Перфоратор или дрель: что выбрать для дома",
    excerpt: "Сравниваем режимы работы, вес и цену — что реально нужно для бытового ремонта.",
    content: "Полный разбор отличий перфоратора и ударной дрели, рекомендации по мощности.",
    coverUrl: cover("#6B6E76", "Инструменты"),
    authorName: "Мастер Игорь П.",
    promoted: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 30,
    views: 87,
    clicks: 0,
    likes: 9,
  },
  {
    id: "art-5",
    kind: "article",
    topic: "legal",
    title: "Что обязательно включить в договор с бригадой",
    excerpt: "Пункты, которые защищают заказчика: сроки, штрафы, порядок приёмки этапов.",
    content: "Юридический разбор типового договора подряда на ремонтные работы.",
    coverUrl: cover("#468966", "Договор"),
    authorName: "Юрист Мария С.",
    promoted: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 50,
    views: 63,
    clicks: 0,
    likes: 27,
  },
  {
    id: "art-6",
    kind: "article",
    topic: "cases",
    title: "Как мы уложились в бюджет на ремонте студии 24 м²",
    excerpt: "Реальный кейс с разбивкой сметы по этапам и фото до/после.",
    content: "Полное описание кейса ремонта студии с разбивкой затрат по категориям.",
    coverUrl: cover("#FF6B1A", "Кейс"),
    authorName: "Блогер Дмитрий Р.",
    promoted: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 70,
    views: 152,
    clicks: 0,
    likes: 5,
  },
  {
    id: "art-7",
    kind: "news",
    topic: "market",
    title: "В городе запустили реестр проверенных бригад",
    excerpt: "Местные власти начали пилотную программу сертификации подрядчиков.",
    content: "Подробности программы сертификации и как в неё попасть.",
    coverUrl: cover("#2B2D31", "Новости"),
    authorName: "Редакция UMELO",
    promoted: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 90,
    views: 45,
    clicks: 0,
    likes: 3,
  },
  {
    id: "art-8",
    kind: "article",
    topic: "howto",
    title: "7 вопросов, которые стоит задать мастеру перед началом работ",
    excerpt: "Как отличить надёжного исполнителя ещё на этапе переговоров.",
    content: "Список из семи вопросов с пояснением, что означает каждый ответ.",
    coverUrl: cover("#468966", "Как выбрать"),
    authorName: "Блогер Дмитрий Р.",
    promoted: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 120,
    views: 119,
    clicks: 0,
    likes: 22,
  },
  {
    id: "art-9",
    kind: "video",
    topic: "howto",
    title: "Видео: как быстро выровнять стены под покраску",
    excerpt: "10-минутный ролик с показом инструмента и техники нанесения шпаклёвки.",
    content: "Видео-инструкция по выравниванию стен своими руками.",
    coverUrl: cover("#2B2D31", "▶ Видео"),
    authorName: "Блогер Дмитрий Р.",
    promoted: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 20,
    views: 276,
    clicks: 0,
    likes: 38,
    linkUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
];
